### PR TITLE
Update lp9.c

### PR DESCRIPTION
**Pull request by ankitagrawal001**

### CODE REVIEW

**Comment by Amanskywalker** [comment]
Sorry man i can't accept your request. Both program are same You only changing the range of matrix.
So try some thing innovative and next time send request in Alternate branch not in master.

**Comment by ankitagrawal001** [comment]
Your, program is not working. Output is wrong.

**Comment by melrick8196** [comment]
@ankitagrawal001  could you mention your input and output statements and be more specific.

**Comment by Amanskywalker** [comment]
@ankitagrawal001 can you upload screenshots so we have the better idea what the problem you are facing. Please don't forget to mention the input and output (by the program) statements and expected output.

**Pull request closed without merging**
